from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
from PyQt5.QtCore import QTimer, QAbstractTableModel, QVariant, Qt
from PyQt5.QtWidgets import QFileDialog
import pandas as pd
import numpy as np
import time

class Tela_Sensor(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_data)
        self.timer.start(50)  # Atualiza a interface a cada 1 segundo

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: White;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_6.addWidget(self.line_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.T_Bat1_text_25 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(21)
        self.T_Bat1_text_25.setFont(font)
        self.T_Bat1_text_25.setTextFormat(QtCore.Qt.RichText)
        self.T_Bat1_text_25.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Bat1_text_25.setObjectName("T_Bat1_text_25")
        self.verticalLayout_7.addWidget(self.T_Bat1_text_25)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.botao4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.botao4_4.setMinimumSize(QtCore.QSize(100, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.botao4_4.setFont(font)
        self.botao4_4.setStyleSheet("background-color: 272727;;")
        self.botao4_4.setObjectName("botao4_4")
        self.horizontalLayout_5.addWidget(self.botao4_4)
        self.botao4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.botao4_3.setMinimumSize(QtCore.QSize(100, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.botao4_3.setFont(font)
        self.botao4_3.setStyleSheet("background-color: 272727;;")
        self.botao4_3.setObjectName("botao4_3")
        self.horizontalLayout_5.addWidget(self.botao4_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_6.addWidget(self.line_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_2.addWidget(self.line_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setSpacing(1)
        self.verticalLayout_26.setObjectName("verticalLayout_26")

        # graph n° 1 (sensores vibração)
        self.win0 = pg.GraphicsLayoutWidget(self.centralwidget)
        self.verticalLayout_5.addWidget(self.win0)
        self.plot0 = self.win0.addPlot(title="Sensor Ultrassonico")
        self.plot0.setLabel('left', 'Distancia')
        self.plot0.setLabel('bottom', 'Tempo', units='s')
        self.curve0 = self.plot0.plot(pen='y')
        self.data0 = []
        self.ptr0 = 0
        self.plot0.setYRange(0, 200)
        self.plot0.setXRange(0, 200 )

        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.T_Bat1_text_24 = QtWidgets.QLabel(self.centralwidget)
        self.T_Bat1_text_24.setMinimumSize(QtCore.QSize(54, 21))
        self.T_Bat1_text_24.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.T_Bat1_text_24.setFont(font)
        self.T_Bat1_text_24.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Bat1_text_24.setObjectName("T_Bat1_text_24")
        self.horizontalLayout_48.addWidget(self.T_Bat1_text_24)
        self.verticalLayout_26.addLayout(self.horizontalLayout_48)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_26.addWidget(self.line_10)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_49.addWidget(self.line_6)
        self.lcd_Ultrassonico = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Ultrassonico.setMinimumSize(QtCore.QSize(250, 85))
        self.lcd_Ultrassonico.setStyleSheet("background-color: Green;")
        self.lcd_Ultrassonico.setObjectName("lcdBat_2")
        self.horizontalLayout_49.addWidget(self.lcd_Ultrassonico)
        self.label_83 = QtWidgets.QLabel(self.centralwidget)
        self.label_83.setMinimumSize(QtCore.QSize(70, 71))
        self.label_83.setMaximumSize(QtCore.QSize(57, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_83.setFont(font)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_49.addWidget(self.label_83)
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.horizontalLayout_49.addWidget(self.line_22)
        self.verticalLayout_26.addLayout(self.horizontalLayout_49)
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_26.addWidget(self.line_25)
        self.verticalLayout_5.addLayout(self.verticalLayout_26)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(390, 361))
        self.label_9.setMaximumSize(QtCore.QSize(648, 484))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("./Arquivos/Imagens/IrisCareSoluctions (1).png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(131, 45))
        self.label_2.setMaximumSize(QtCore.QSize(131, 45))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./Arquivos/Imagens/download.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_20.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.T_Bat1_text_25.setText(_translate("MainWindow", "IrisCareSolutions"))
        self.botao4_4.setText(_translate("MainWindow", "Sensor"))

        self.botao4_3.setText(_translate("MainWindow", "Integrantes"))
        self.botao4_3.clicked.connect(self.open_integrantes)

        self.T_Bat1_text_24.setText(_translate("MainWindow", "Ultrassonico"))
        self.label_83.setText(_translate("MainWindow", "cm"))

    def update_data(self):
        Values = data(df)
        ValorLCD = Values.loc[0, 'distancia']

        self.lcd_Ultrassonico.display(ValorLCD)

        # Garante que apenas os últimos 200 valores sejam mantidos
        self.data0 = Values['distancia'].head(200)

        # Atualiza os gráficos com os novos conjuntos de dados
        self.curve0.setData(self.data0)




    def open_integrantes(self):

        self.Integrantes_window = Tela_Integrantes()
        self.Integrantes_window.setupUi(self.Integrantes_window)  # Inicializa a tela do inversor
        self.hide()  # Esconde a tela atual
        self.Integrantes_window.showMaximized()  # Mostra a janela do inversor em tela cheia

class Tela_Integrantes(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # Inicia o timer para atualizar a interface periodicamente
        # self.timer = QTimer()
        # self.timer.timeout.connect(self.update_data)
        # self.timer.start(50)  # Atualiza a interface a cada 1 segundo
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 724)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: White;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_6.addWidget(self.line_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.T_Bat1_text_25 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(21)
        self.T_Bat1_text_25.setFont(font)
        self.T_Bat1_text_25.setTextFormat(QtCore.Qt.RichText)
        self.T_Bat1_text_25.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Bat1_text_25.setObjectName("T_Bat1_text_25")
        self.verticalLayout_7.addWidget(self.T_Bat1_text_25)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botao4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.botao4_4.setMinimumSize(QtCore.QSize(100, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.botao4_4.setFont(font)
        self.botao4_4.setStyleSheet("background-color: 272727;;")
        self.botao4_4.setObjectName("botao4_4")
        self.horizontalLayout.addWidget(self.botao4_4)
        self.botao4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.botao4_3.setMinimumSize(QtCore.QSize(100, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.botao4_3.setFont(font)
        self.botao4_3.setStyleSheet("background-color: 272727;;")
        self.botao4_3.setObjectName("botao4_3")
        self.horizontalLayout.addWidget(self.botao4_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_2.addWidget(self.line_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(131, 45))
        self.label_2.setMaximumSize(QtCore.QSize(131, 45))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./Arquivos/Imagens/download.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_20.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.T_Bat1_text_25.setText(_translate("MainWindow", "IrisCareSolutions"))
        self.botao4_4.setText(_translate("MainWindow", "Sensor"))
        self.botao4_4.clicked.connect(self.open_sensor)

        self.botao4_3.setText(_translate("MainWindow", "Integrantes"))
        self.label.setText(_translate("MainWindow", "RM: 93915 -  JAELSON DOS SANTOS\n"
"\n"
"RM: 94311 - MARCOS BILOBRAM\n"
"\n"
"RM: 96320 - NATHÁLIA MAIA\n"
"\n"
"RM: 94972 - RAFAELA DA SILVA\n"
"\n"
"RM: 93613 - VINICIUS DE OLIVEIRA"))

    def open_sensor(self):

        self.Integrantes_window = Tela_Sensor()
        self.Integrantes_window.setupUi(self.Integrantes_window)  # Inicializa a tela do inversor
        self.hide()  # Esconde a tela atual
        self.Integrantes_window.showMaximized()  # Mostra a janela do inversor em tela cheia

def data(df):
        # Generate a random number
    random_number = np.random.randint(0, 100)

    # Add the number to the top of the DataFrame
    df.loc[-1] = random_number
    df.index = df.index + 1
    df = df.sort_index()

    return df

if __name__ == "__main__":
    import sys
    
    df = pd.DataFrame(columns=['distancia'])


    app = QtWidgets.QApplication(sys.argv)
    MainWindow = Tela_Sensor()
    MainWindow.setupUi(MainWindow)
    MainWindow.showMaximized()

    sys.exit(app.exec_())
